//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RavKav : DbContext
    {
        public RavKav()
            : base("name=RavKav")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardTbl> CardTbls { get; set; }
        public virtual DbSet<ProfilsTbl> ProfilsTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransitTbl> TransitTbls { get; set; }
        public virtual DbSet<TravelsTbl> TravelsTbls { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
